"""Provenance Guard — AI content attribution Flask API.

Submission flow (M3):
    POST /submit
        -> Signal 1 (Groq LLM, float 0-1)
        -> combined confidence (placeholder: just the LLM score for now)
        -> transparency label
        -> audit log (SQLite)
        -> JSON response

Signal 2 (stylometric) and the real confidence-combination logic arrive in M4;
`stylometric_score` is stored as NULL until then.
"""

import json
import os
import re
import sqlite3
import string
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "audit_log.db")
GROQ_MODEL = "llama-3.3-70b-versatile"

app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    storage_uri="memory://",
)


# --------------------------------------------------------------------------- #
# Database
# --------------------------------------------------------------------------- #
def init_db():
    """Create the audit_log table if it does not already exist."""
    conn = sqlite3.connect(DB_PATH)
    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS audit_log (
                content_id        TEXT PRIMARY KEY,
                creator_id        TEXT,
                timestamp         TEXT,
                attribution       TEXT,
                confidence        REAL,
                llm_score         REAL,
                stylometric_score REAL,
                status            TEXT DEFAULT 'classified',
                appeal_reasoning  TEXT,
                appeal_timestamp  TEXT
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


# --------------------------------------------------------------------------- #
# Detection Signal 1 — LLM (Groq)
# --------------------------------------------------------------------------- #
LLM_SYSTEM_PROMPT = (
    "You are an AI content detection system. Assess whether the user-provided "
    "text was generated by an AI language model. Consider semantic and "
    "stylistic coherence, predictability, vocabulary patterns, and overall "
    'voice. Respond ONLY with valid JSON in exactly this form: '
    '{"ai_probability": <float between 0 and 1>, "reasoning": "<brief '
    'explanation>"} where ai_probability is the probability the text is '
    "AI-generated (1.0 = certainly AI, 0.0 = certainly human). Output nothing "
    "but the JSON object."
)


def llm_signal(text):
    """Call Groq and return the probability (float 0.0-1.0) the text is AI-generated.

    Raises on client/transport errors so the caller can return HTTP 500.
    """
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    completion = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": LLM_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,
        response_format={"type": "json_object"},
    )
    raw = completion.choices[0].message.content
    parsed = json.loads(raw)
    score = float(parsed["ai_probability"])
    # Clamp into range in case the model drifts outside [0, 1].
    return max(0.0, min(1.0, score))


# --------------------------------------------------------------------------- #
# Detection Signal 2 — Stylometric heuristics (pure Python, no external libs)
# --------------------------------------------------------------------------- #
def _interpolate(value, human_bound, ai_bound):
    """Map `value` to an AI score in [0, 1] by linear interpolation.

    `human_bound` is the value at which the score is 0.0 (very human-like) and
    `ai_bound` the value at which the score is 1.0 (very AI-like). Works whether
    the human bound is the high end (variance, TTR, punctuation) or not.
    """
    score = (value - human_bound) / (ai_bound - human_bound)
    return max(0.0, min(1.0, score))


def stylometric_signal(text):
    """Return the probability (float 0.0-1.0) the text is AI-generated.

    Combines three equally weighted sub-metrics: sentence length variance,
    type-token ratio, and informal punctuation density.
    """
    # Sub-metric A — sentence length variance.
    sentences = [s.strip() for s in re.split(r"[.!?]", text) if s.strip()]
    if len(sentences) < 2:
        variance_score = 0.5
    else:
        word_counts = [len(s.split()) for s in sentences]
        mean = sum(word_counts) / len(word_counts)
        std_dev = (sum((c - mean) ** 2 for c in word_counts) / len(word_counts)) ** 0.5
        variance_score = _interpolate(std_dev, human_bound=15.0, ai_bound=2.0)

    # Sub-metric B — type-token ratio (TTR).
    tokens = [t.strip(string.punctuation).lower() for t in text.split()]
    tokens = [t for t in tokens if t]
    if not tokens:
        ttr_score = 0.5
    else:
        ttr = len(set(tokens)) / len(tokens)
        ttr_score = _interpolate(ttr, human_bound=0.85, ai_bound=0.50)

    # Sub-metric C — informal punctuation density.
    informal_chars = "!?…—–()\"'"
    informal_count = sum(text.count(ch) for ch in informal_chars)
    informal_count += text.count("...")  # count ellipsis spelled with periods
    total_words = len(text.split())
    density = informal_count / max(total_words, 1)
    punct_score = _interpolate(density, human_bound=0.15, ai_bound=0.02)

    return (variance_score + ttr_score + punct_score) / 3.0


# --------------------------------------------------------------------------- #
# Confidence scoring + transparency labels
# --------------------------------------------------------------------------- #
def combine_confidence(llm_score, stylometric_score):
    """Combine detection signals into a single confidence score.

    Weighted average: LLM 0.65 / stylometric 0.35. The LLM signal carries more
    weight because it captures semantic coherence the heuristics miss, while the
    stylometric signal provides independent structural verification.
    """
    return (0.65 * llm_score) + (0.35 * stylometric_score)


def make_label(confidence):
    """Map a confidence score to (attribution, reader-facing label text)."""
    pct = f"{round(confidence * 100)}%"
    if confidence >= 0.75:
        return (
            "likely_ai",
            f"⚠️ AI-Generated Content — Our system is highly confident ({pct}) "
            "this content was AI-generated. If you are the creator and believe "
            "this is incorrect, you can submit an appeal.",
        )
    if confidence >= 0.45:
        return (
            "uncertain",
            f"? Attribution Unclear — Our system cannot confidently determine "
            "whether this content is human- or AI-written (confidence: "
            f"{pct}). The creator may appeal if they believe the "
            "classification is inaccurate.",
        )
    return (
        "likely_human",
        f"✓ Likely Human-Written — Our analysis suggests this content was "
        f"written by a person ({pct} confidence). Attribution signals indicate "
        "authentic human authorship.",
    )


# --------------------------------------------------------------------------- #
# Endpoints
# --------------------------------------------------------------------------- #
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not creator_id:
        return jsonify({"error": "Both 'text' and 'creator_id' are required."}), 400

    try:
        llm_score = llm_signal(text)
    except Exception as exc:  # noqa: BLE001 - surface any Groq/transport failure
        return jsonify({"error": f"Detection signal failed: {exc}"}), 500

    stylometric_score = stylometric_signal(text)
    confidence = combine_confidence(llm_score, stylometric_score)
    attribution, label = make_label(confidence)

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    conn = get_db()
    try:
        conn.execute(
            """
            INSERT INTO audit_log (
                content_id, creator_id, timestamp, attribution, confidence,
                llm_score, stylometric_score, status,
                appeal_reasoning, appeal_timestamp
            ) VALUES (?, ?, ?, ?, ?, ?, ?, 'classified', NULL, NULL)
            """,
            (
                content_id,
                creator_id,
                timestamp,
                attribution,
                confidence,
                llm_score,
                stylometric_score,
            ),
        )
        conn.commit()
    finally:
        conn.close()

    return jsonify(
        {
            "content_id": content_id,
            "attribution": attribution,
            "confidence": confidence,
            "label": label,
            "signal_scores": {"llm": llm_score, "stylometric": stylometric_score},
        }
    )


@app.route("/log", methods=["GET"])
def get_log():
    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT 50"
        ).fetchall()
    finally:
        conn.close()

    return jsonify({"entries": [dict(row) for row in rows]})


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")

    if not content_id or not creator_reasoning:
        return (
            jsonify(
                {"error": "Both 'content_id' and 'creator_reasoning' are required."}
            ),
            400,
        )

    conn = get_db()
    try:
        row = conn.execute(
            "SELECT content_id FROM audit_log WHERE content_id = ?",
            (content_id,),
        ).fetchone()
        if row is None:
            return jsonify({"error": "content_id not found"}), 404

        appeal_timestamp = datetime.now(timezone.utc).isoformat()
        conn.execute(
            """
            UPDATE audit_log
            SET status = 'under_review',
                appeal_reasoning = ?,
                appeal_timestamp = ?
            WHERE content_id = ?
            """,
            (creator_reasoning, appeal_timestamp, content_id),
        )
        conn.commit()
    finally:
        conn.close()

    return (
        jsonify(
            {
                "status": "under_review",
                "message": (
                    "Your appeal has been received and logged. A human reviewer "
                    "will examine your submission."
                ),
                "content_id": content_id,
            }
        ),
        200,
    )


init_db()


if __name__ == "__main__":
    app.run(port=5000, debug=True)
